
// Objective-C API for talking to the following Go packages
//
//	github.com/bellistech/cs/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Cscore_FRAMEWORK_H__
#define __Cscore_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
