// Objective-C API for talking to github.com/bellistech/cs/mobile Go package.
//   gobind -lang=objc github.com/bellistech/cs/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * MobileBookmarkIsStarred returns true if a topic is bookmarked.
 */
FOUNDATION_EXPORT BOOL MobileMobileBookmarkIsStarred(NSString* _Nullable topic);

/**
 * MobileBookmarkList returns all bookmarks as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileBookmarkList(void);

/**
 * MobileBookmarkToggle toggles a bookmark, returning state as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileBookmarkToggle(NSString* _Nullable topic);

/**
 * MobileCalcEval evaluates an arithmetic expression and returns JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileCalcEval(NSString* _Nullable expr);

/**
 * MobileCategoriesJSON returns all categories with counts as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileCategoriesJSON(void);

/**
 * MobileCategoryTopicsJSON returns topics in a category as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileCategoryTopicsJSON(NSString* _Nullable category);

/**
 * MobileCompareJSON compares two topics as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileCompareJSON(NSString* _Nullable nameA, NSString* _Nullable nameB);

/**
 * MobileGetDetailJSON returns a detail page as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileGetDetailJSON(NSString* _Nullable name);

/**
 * MobileGetSheetJSON returns a single sheet as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileGetSheetJSON(NSString* _Nullable name);

/**
 * MobileInit initializes the Go core with embedded sheet data.
Must be called once from application:didFinishLaunchingWithOptions:
before any other function in this package.
 */
FOUNDATION_EXPORT BOOL MobileMobileInit(NSError* _Nullable* _Nullable error);

/**
 * MobileLearnPathJSON returns topics ordered by prerequisites as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileLearnPathJSON(NSString* _Nullable category);

/**
 * MobileListTopicsJSON returns all topics as a JSON array.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileListTopicsJSON(void);

/**
 * MobileRandomTopicJSON returns a random sheet as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileRandomTopicJSON(void);

/**
 * MobileRelatedJSON returns related topics as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileRelatedJSON(NSString* _Nullable name);

/**
 * MobileRenderMarkdownToHTML converts markdown to HTML as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileRenderMarkdownToHTML(NSString* _Nullable md);

/**
 * MobileSearchJSON searches sheets and returns results as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileSearchJSON(NSString* _Nullable query);

/**
 * MobileSetDataDir sets the app sandbox directory for bookmarks.
 */
FOUNDATION_EXPORT void MobileMobileSetDataDir(NSString* _Nullable path);

/**
 * MobileStatsJSON returns statistics as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileStatsJSON(void);

/**
 * MobileSubnetCalc parses a CIDR and returns subnet info as JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileSubnetCalc(NSString* _Nullable input);

/**
 * MobileVerifyJSON checks math in a detail page and returns JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileMobileVerifyJSON(NSString* _Nullable topic);

#endif
