#!/bin/bash
# Build a simple top-level index of all sheets, by category, with each sheet's title
cd /Users/govan/tmp/projects/cheat_sheet
{
  echo "# cs — Sheet Index"
  echo ""
  echo "Every cheatsheet in cs, organized by category. Run \`cs <name>\` to view a sheet, or \`cs -s <query>\` to search."
  echo ""
  echo "Generated by build-index.sh."
  echo ""
  for dir in $(find sheets -mindepth 1 -maxdepth 1 -type d | sort); do
    cat=$(basename "$dir")
    # Skip if no markdown files
    if ! ls "$dir"/*.md > /dev/null 2>&1; then
      continue
    fi
    pretty_cat=$(echo "$cat" | tr '-' ' ' | awk '{for(i=1;i<=NF;i++)$i=toupper(substr($i,1,1))substr($i,2)}1')
    echo "## $pretty_cat"
    echo ""
    for f in "$dir"/*.md; do
      name=$(basename "$f" .md)
      # Get title (first H1) — fall back to name
      title=$(head -3 "$f" | grep -oE '^# .*' | head -1 | sed 's/^# //')
      [ -z "$title" ] && title="$name"
      # First line after the H1 (the one-liner)
      tagline=$(awk '/^# /{flag=1;next} flag && NF{print;exit}' "$f" | head -c 100)
      echo "- \`cs $name\` — $title"
    done
    echo ""
  done
  echo "## See Also"
  echo ""
  echo "- \`cs -s <query>\` — search across all sheets"
  echo "- \`cs --help\` — full CLI reference"
  echo "- \`cs <topic>\` — view a single sheet"
  echo ""
  echo "## References"
  echo ""
  echo "- This file is generated by \`scripts/build-index.sh\` and embedded as \`sheets/_index.md\`."
} > sheets/_index.md
echo "Wrote sheets/_index.md"
wc -l sheets/_index.md
